### PR TITLE
fix: Removed call to _count_relevant_tb_levels

### PR DESCRIPTION
**Pull request by walidsi**
Removed call to _count_relevant_tb_levels to work with lastest version of unittest

### CODE REVIEW

**Comment by SofieneOuerdiane** [comment]
Hello, 
is there some issues blocking the merge of this pull request ?

**Comment by KamRosEmer** [comment]
Hi, 
I am also waiting for that fix

**Review by prempiyush — COMMENTED** [review]
The `if` condition is now meaningless. The complete `if..else` can just be replaced with `msg_lines = traceback.format_exception(exctype, value, tb)`

**Comment by aurelienlair** [comment]
Yeah actually I'm not waiting, but I just followed a course which is using this package and I got that issue too. Maybe it would be time to release that fix..?

**Comment by TXTT2016** [comment]
how about this merge request? I have met this problem.

```code
'HtmlTestResult' object has no attribute '_count_relevant_tb_levels'. Did you mean: '_is_relevant_tb_level'
```

**Comment by Matindo** [comment]
Is there anyone out there who can merge this and issue a new release, please? I'm having the same problem as @TXTT2016 and cannot move unless this is cleared, or I have to look for another way to report🤦‍♂️

**Comment by thomaslrg** [comment]
Looking forward to the release, @oldani. The merged PR will be a great addition!

**Comment by rafoelhonrado** [comment]
This was merged? Because when I install using pip I am still getting the old version

**Comment by thomaslrg** [comment]
> This was merged? Because when I install using pip I am still getting the old version

@rafoelhonrado Yes it's been merged to the `master` branch of the repository, but the latest release (v1.2.1) of the Python package was on dated Sep 9, 2019.

You can install the package from the GitHub source using

```bash
$ pip install git+https://github.com/oldani/HtmlTestRunner@master
```

or add the following to your `requirements.txt`

```
html-testRunner @ git+https://github.com/oldani/HtmlTestRunner@master
```

**Comment by bbassett-tibco** [comment]
I'd second the notion that a new release to PyPI is probably warranted now that Python 3.13 has released (with the updates to unittest).  Unfortunately, due to our dependency management processes, we're not allowed to depend on prereleases of other components (so @thomaslrg's workaround using the `git+https` URL is out for us).

**Pull request merged**
